sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
matrix:
  include:
    - node_js: "7"
      env: TEST_SUITE=coverage
    - node_js: "7"
      env: TEST_SUITE=lint
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE
